//Test of Card Class
var obj = require('../Models/Card.js')

var card1 = new obj()
card1.setId(1)
card1.setName(`Arrota Lodo`)
card1.setType(`Neutro`)
card1.setDescription(`Ele arrota lodo em você`)
card1.setCost('3')
card1.setBaseAttack('2')
card1.setBaseDefense('3')
card1.setBaseEffect()
card1.setMaxAttack('2')
card1.setMaxDefense('3')
card1.setCurrentAttack('2')
card1.setCurrentDefense('3')
card1.setCurrentEffect()
card1.setFrontImage('ArrotaLodo.img')
card1.setBackImage('DeckBack.img')
card1.addStatus(1)
card1.addStatus(2)
card1.addStatus(3)
card1.addStatus(2)
card1.removeStatus(2)
console.log(card1.getId())
console.log(card1.getName())
console.log(card1.getType())
console.log(card1.getDescription())
console.log(card1.getCost())
console.log(card1.getBaseAttack())
console.log(card1.getBaseDefense())
console.log(card1.getBaseEffect())
console.log(card1.getMaxAttack())
console.log(card1.getMaxDefense())
console.log(card1.getCurrentAttack())
console.log(card1.getCurrentDefense())
console.log(card1.getCurrentEffect())
console.log(card1.getFrontImage())
console.log(card1.getBackImage())

card2 = new obj()

card2.Card(2,'Cavalga Lobo', 1,'Um goblin cavalgando um lobo', 2, 3, 1, 2, 3, 1, 3, 1, 2, 'cavalgalobo.img', 'defaultback.img', [2])
var c = card2.save()

card3 = new obj()
card3.load(card3, '{"Id":2,"Name":"Cavalga Lobo","Type":1,"Description":"Um goblin cavalgando um lobo","Cost":2,"BaseAttack":3,"BaseDefense":1,"BaseEffect":2,"MaxAttack":3,"MaxDefense":1,"CurrentAttack":3,"CurrentDefense":1,"CurrentEffect":2,"FrontImage":"cavalgalobo.img","BackImage":"defaultback.img","Status":[2]}')

console.log(card1.save())
console.log(card2.save())
console.log(card3.save())
 
